language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-makeshift' ]; then cd .. && eval "mv $currentfolder generator-makeshift" && cd generator-makeshift; fi

